/********************************************************************************
 * Copyright (C) 2026 TOKENAI.
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License, which is available in the project root.
 *
 * SPDX-License-Identifier: MIT
 ********************************************************************************/
/* eslint-disable max-len */

import { TOKENAI_DEFAULT_HOME_RECIPE } from './archetypes';
import { TokenaiWebsiteType } from './website-types';

/**
 * Type pack: paket konten demo per jenis website — brand contoh fiktif, headline, statistik,
 * keunggulan, dan testimoni yang KHAS jenis itu. Dikonsumsi `demo-preview.ts` lewat opsi
 * `copy` scaffolder, sehingga demo "Restoran" terasa seperti situs restoran sungguhan dan
 * demo "SaaS" seperti produk SaaS — bukan satu template dengan teks yang sama.
 *
 * Dikarang sekali pada waktu authoring (bukan runtime); menambah/menyegarkan kit berarti
 * mengarang ulang paket-paket ini, tanpa biaya token di sisi pengguna.
 */
export interface TokenaiTypePack {
    /** Brand contoh fiktif untuk demo jenis ini. */
    brand: string;
    /** Deskripsi usaha — meta description + subjudul hero (dirangkai `brand — deskripsi`). */
    description: string;
    /**
     * Resep beranda: urutan blok `partials/home/` yang dirakit scaffolder — di sinilah tiap
     * jenis mendapat KOMPOSISI berbeda (varian hero + blok tengah khas), bukan cuma teks.
     */
    recipe: string[];
    /** Timpaan placeholder `{{TK_<KUNCI>}}` arketipe; yang tak ada jatuh ke bawaan scaffolder. */
    copy: Record<string, string>;
}

const PACKS: Record<string, TokenaiTypePack> = {
    'Bisnis / Company Profile': {
        brand: 'Arunika Konsultan',
        description: 'konsultan manajemen dan keuangan untuk UKM yang ingin naik kelas.',
        recipe: ['hero-split', 'logo-band', 'features', 'about-checks', 'quotes-trio', 'cta'],
        copy: {
            TAGLINE: 'Partner bertumbuh untuk bisnis Anda',
            HERO_BADGE: 'Dipercaya 120+ perusahaan',
            HERO_CTA: 'Konsultasi Gratis',
            HERO_IMG: 'Tim konsultan',
            HERO_CARD_T: 'Sejak 2012',
            HERO_CARD_S: 'Mendampingi ratusan UKM',
            ABOUT_IMG: 'Kantor kami',
            STAT1_V: '13+', STAT1_L: 'Tahun berpengalaman',
            STAT2_V: '120+', STAT2_L: 'Klien aktif',
            STAT3_V: '340+', STAT3_L: 'Proyek selesai',
            STAT4_V: '96%', STAT4_L: 'Klien memperpanjang',
            FEAT1_T: 'Analisis mendalam', FEAT1_D: 'Rekomendasi berbasis data, bukan tebakan.',
            FEAT2_T: 'Pendampingan penuh', FEAT2_D: 'Kami ikut turun tangan sampai eksekusi selesai.',
            FEAT3_T: 'Laporan transparan', FEAT3_D: 'Perkembangan terukur, dilaporkan tiap bulan.',
            HOME_ABOUT: 'Berawal dari dua konsultan yang gelisah melihat UKM potensial jalan di tempat, kini kami menjadi tim lintas disiplin yang mendampingi bisnis dari strategi sampai eksekusi.',
            CHECK1: 'Konsultan bersertifikat dengan pengalaman industri.',
            CHECK2: 'Kontrak fleksibel — mulai dari satu proyek kecil.',
            CHECK3: 'Jaminan kerahasiaan data klien.',
            QUOTE1: 'Enam bulan didampingi, arus kas kami akhirnya sehat dan tim jauh lebih tertata.',
            QUOTE2: 'Rekomendasinya konkret dan bisa langsung dieksekusi. Bukan sekadar slide presentasi.',
            QUOTE3: 'Dari pembukuan berantakan sampai siap mengajukan pendanaan — semuanya dikawal.',
            CTA_T: 'Diskusikan kebutuhan bisnis Anda',
            CTA_S: 'Sesi konsultasi pertama gratis, tanpa komitmen.',
            ABOUT_STORY1: 'Arunika lahir dari meja kecil di sudut coworking space, ketika dua konsultan memutuskan berhenti membuat laporan yang hanya jadi pajangan dan mulai mendampingi eksekusi.',
            ABOUT_STORY2: 'Kini kami tim lintas disiplin — keuangan, operasi, dan pemasaran — dengan satu ukuran keberhasilan: angka klien yang membaik.',
            VAL1_T: 'Jujur pada data', VAL1_D: 'Rekomendasi kami mengikuti angka, bukan selera.',
            VAL2_T: 'Ikut turun tangan', VAL2_D: 'Strategi tanpa eksekusi adalah wacana.',
            VAL3_T: 'Rahasia terjaga', VAL3_D: 'Data klien tidak pernah keluar dari ruang kerja.',
            SVC1_T: 'Penataan Keuangan', SVC1_D: 'Rapikan arus kas, pembukuan, dan struktur biaya sampai layak diaudit.',
            SVC2_T: 'Strategi Pertumbuhan', SVC2_D: 'Peta jalan ekspansi berbasis data pasar — untuk naik kelas, bukan sekadar bertahan.',
            SVC3_T: 'Pendampingan Operasional', SVC3_D: 'SOP, struktur tim, dan KPI yang membuat bisnis jalan tanpa Anda lembur.',
            FAQ1_Q: 'Bagaimana memulai kerja sama?', FAQ1_A: 'Jadwalkan sesi konsultasi gratis — kami petakan masalahnya dulu sebelum bicara kontrak.',
            FAQ2_Q: 'Berapa biaya jasanya?', FAQ2_A: 'Tergantung lingkup: proyek tunggal atau pendampingan bulanan. Penawaran selalu tertulis di awal.',
            FAQ3_Q: 'Apakah cocok untuk usaha kecil?', FAQ3_A: 'Justru mayoritas klien kami UKM — paket kami disusun untuk skala itu.',
            FAQ4_Q: 'Berapa lama sampai terasa hasilnya?', FAQ4_A: 'Perbaikan proses terasa dalam hitungan minggu; dampak angka umumnya 3–6 bulan.',
            CONTACT_SUB: 'Ceritakan tantangan bisnis Anda — sesi pertama gratis.',
            LOGOS_T: 'Dipercaya perusahaan lintas industri',
            LOGO1: 'Kopi Anara', LOGO2: 'Gaya Living', LOGO3: 'PT Sinar Baja', LOGO4: 'Rumah Modest', LOGO5: 'Toko Delapan'
        }
    },
    'E-commerce / Toko Online': {
        brand: 'Lokalane',
        description: 'kurasi produk kerajinan lokal terbaik, dikirim langsung dari perajinnya.',
        recipe: ['hero-visual', 'product-strip', 'features', 'quote-single', 'cta'],
        copy: {
            TAGLINE: 'Belanja karya lokal, dukung perajinnya',
            HERO_BADGE: 'Gratis ongkir min. Rp150rb',
            HERO_CTA: 'Belanja Sekarang',
            HERO_IMG: 'Produk unggulan',
            HERO_CARD_T: '10.000+ pesanan',
            HERO_CARD_S: 'Terkirim ke seluruh Indonesia',
            ABOUT_IMG: 'Perajin mitra',
            STAT1_V: '250+', STAT1_L: 'Perajin mitra',
            STAT2_V: '1.800+', STAT2_L: 'Produk kurasi',
            STAT3_V: '10rb+', STAT3_L: 'Pesanan terkirim',
            STAT4_V: '4,9', STAT4_L: 'Rating toko',
            FEAT1_T: 'Kurasi ketat', FEAT1_D: 'Hanya produk terbaik dari tiap perajin yang lolos.',
            FEAT2_T: 'Kirim cepat & aman', FEAT2_D: 'Dikemas rapi, sampai 1–3 hari kerja.',
            FEAT3_T: 'Tukar mudah', FEAT3_D: '7 hari tukar barang tanpa ribet.',
            HOME_ABOUT: 'Kami keliling sentra kerajinan mencari karya terbaik, lalu membawanya ke etalase online supaya perajin mendapat harga yang pantas dan Anda mendapat barang yang berkarakter.',
            CHECK1: 'Setiap pembelian menghidupi perajin lokal.',
            CHECK2: 'Foto produk asli, bukan hasil rekayasa.',
            CHECK3: 'Pembayaran aman berbagai metode.',
            QUOTE1: 'Kualitas barangnya melebihi foto. Kemasannya juga niat banget.',
            QUOTE2: 'Sudah lima kali repeat order, tidak pernah kecewa.',
            QUOTE3: 'Senang bisa belanja sambil tahu barangnya bikinan siapa.',
            CTA_T: 'Temukan barang berkarakter',
            CTA_S: 'Koleksi baru tiap minggu — jangan sampai kehabisan.',
            ABOUT_STORY1: 'Lokalane dimulai dari satu koper penuh kerajinan yang kami bawa pulang dari perjalanan ke Jogja — semuanya habis dipesan teman dalam seminggu.',
            ABOUT_STORY2: 'Sekarang kami bekerja langsung dengan ratusan perajin, tanpa tengkulak, dengan pembagian harga yang tertulis jelas.',
            VAL1_T: 'Adil ke perajin', VAL1_D: 'Harga beli disepakati terbuka, dibayar di muka.',
            VAL2_T: 'Jujur ke pembeli', VAL2_D: 'Foto asli, deskripsi apa adanya, cacat disebutkan.',
            VAL3_T: 'Ramah lingkungan', VAL3_D: 'Kemasan daur ulang, tanpa plastik sekali pakai.',
            FAQ1_Q: 'Berapa lama pengiriman pesanan?', FAQ1_A: 'Barang ready dikirim H+1; barang pre-order 7–14 hari karena dibuat setelah dipesan.',
            FAQ2_Q: 'Apakah bisa tukar atau retur?', FAQ2_A: 'Bisa, 7 hari sejak diterima untuk barang tidak sesuai deskripsi — ongkir kami tanggung.',
            FAQ3_Q: 'Metode pembayaran apa saja?', FAQ3_A: 'Transfer bank, e-wallet, kartu, dan COD untuk kota tertentu.',
            FAQ4_Q: 'Apakah tiap barang benar-benar handmade?', FAQ4_A: 'Ya — karena itu tiap barang bisa sedikit berbeda, dan justru itu nilainya.',
            CONTACT_SUB: 'Butuh bantuan soal pesanan? Tim kami balas cepat di jam kerja.',
            CATALOG_SUB: 'Kurasi terbaru dari perajin di seluruh Indonesia.',
            CARD_META: '4,9 · Terjual 250+',
            CARD_DESC: 'Dibuat tangan oleh perajin mitra, stok terbatas.',
            CARD_PRICE: 'Rp149.000',
            CARD_CTA: 'Lihat',
            CARD_WORD: 'Produk',
            STRIP_T: 'Produk terlaris minggu ini',
            STRIP_S: 'Yang paling cepat habis — dibuat terbatas oleh perajinnya.'
        }
    },
    'Portofolio': {
        brand: 'Studio Renjana',
        description: 'studio desain grafis dan branding untuk merek yang ingin tampil beda.',
        recipe: ['hero-minimal', 'work-masonry', 'quote-single', 'cta'],
        copy: {
            TAGLINE: 'Desain yang bicara sebelum Anda',
            HERO_BADGE: 'Studio desain & branding',
            HERO_CTA: 'Ajak Kolaborasi',
            HERO_IMG: 'Karya terbaru',
            HERO_CARD_T: '80+ proyek',
            HERO_CARD_S: 'Untuk merek dalam & luar negeri',
            ABOUT_IMG: 'Suasana studio',
            STAT1_V: '8', STAT1_L: 'Tahun berkarya',
            STAT2_V: '80+', STAT2_L: 'Proyek selesai',
            STAT3_V: '12', STAT3_L: 'Penghargaan desain',
            STAT4_V: '95%', STAT4_L: 'Klien kembali',
            FEAT1_T: 'Riset dulu, desain kemudian', FEAT1_D: 'Setiap karya berangkat dari pemahaman merek.',
            FEAT2_T: 'Proses kolaboratif', FEAT2_D: 'Anda dilibatkan di tiap tonggak penting.',
            FEAT3_T: 'Serah terima rapi', FEAT3_D: 'File master, panduan, dan aset siap pakai.',
            HOME_ABOUT: 'Studio kecil dengan standar besar: kami hanya mengambil beberapa proyek dalam satu waktu agar setiap merek mendapat perhatian penuh.',
            CHECK1: 'Portofolio lintas industri — F&B, fashion, teknologi.',
            CHECK2: 'Timeline jelas dengan tonggak yang disepakati.',
            CHECK3: 'Revisi terstruktur, bukan tanpa ujung.',
            QUOTE1: 'Identitas baru kami langsung menaikkan kepercayaan calon klien.',
            QUOTE2: 'Prosesnya rapi, presentasinya meyakinkan, hasilnya di atas ekspektasi.',
            QUOTE3: 'Satu-satunya studio yang benar-benar mendalami bisnis kami dulu.',
            CTA_T: 'Punya proyek menarik?',
            CTA_S: 'Ceritakan idenya — kami balas dalam 1×24 jam.',
            ABOUT_STORY1: 'Renjana berdiri tahun 2018 dari dua desainer yang bosan melihat merek lokal tampil seadanya padahal produknya luar biasa.',
            ABOUT_STORY2: 'Kami sengaja tetap kecil: sedikit proyek, perhatian penuh, hasil yang membuat kami sendiri iri.',
            VAL1_T: 'Riset sebelum rupa', VAL1_D: 'Desain yang benar lahir dari pemahaman, bukan tren.',
            VAL2_T: 'Berani berbeda', VAL2_D: 'Aman itu musuh diingat orang.',
            VAL3_T: 'Tuntas sampai detail', VAL3_D: 'Kerning pun kami perdebatkan.',
            FAQ1_Q: 'Bagaimana proses kerjanya?', FAQ1_A: 'Diskusi brief → riset & konsep → presentasi arah desain → eksekusi → serah terima file master dan panduan.',
            FAQ2_Q: 'Berapa lama satu proyek branding?', FAQ2_A: 'Umumnya 4–8 minggu tergantung lingkup — timeline disepakati sebelum mulai.',
            FAQ3_Q: 'Apakah menerima proyek kecil?', FAQ3_A: 'Ya, selama brief-nya jelas — banyak karya favorit kami justru proyek kecil.',
            FAQ4_Q: 'Berapa kali revisi?', FAQ4_A: 'Dua putaran besar per tahap, terstruktur — supaya energi habis untuk kualitas, bukan bolak-balik.',
            CONTACT_SUB: 'Ceritakan proyekmu — brief singkat pun cukup untuk mulai.',
            CATALOG_SUB: 'Pilihan karya yang paling kami banggakan.',
            CARD_META: 'Branding · 2026',
            CARD_DESC: 'Identitas visual lengkap: logo, tipografi, dan panduan merek.',
            CARD_PRICE: 'Studi kasus',
            CARD_CTA: 'Lihat Karya',
            CARD_WORD: 'Karya',
            STRIP_T: 'Karya terpilih',
            STRIP_S: 'Sebagian proyek yang paling menggambarkan cara kami bekerja.'
        }
    },
    'Landing Page': {
        brand: 'Nadicare',
        description: 'aplikasi pengingat kesehatan harian untuk Anda dan keluarga.',
        recipe: ['hero-centered', 'features', 'stats', 'quotes-trio', 'cta'],
        copy: {
            TAGLINE: 'Hidup sehat dimulai dari pengingat kecil',
            HERO_BADGE: 'Baru — versi 2.0 telah rilis',
            HERO_CTA: 'Coba Gratis',
            HERO_IMG: 'Tampilan aplikasi',
            HERO_CARD_T: '50rb+ unduhan',
            HERO_CARD_S: 'Rating 4,8 di app store',
            ABOUT_IMG: 'Di balik layar',
            STAT1_V: '50rb+', STAT1_L: 'Pengguna aktif',
            STAT2_V: '4,8', STAT2_L: 'Rating aplikasi',
            STAT3_V: '92%', STAT3_L: 'Merasa lebih teratur',
            STAT4_V: '14 hari', STAT4_L: 'Uji coba gratis',
            FEAT1_T: 'Pengingat pintar', FEAT1_D: 'Menyesuaikan jadwal dan kebiasaan Anda.',
            FEAT2_T: 'Pantau keluarga', FEAT2_D: 'Satu akun untuk orang tua dan anak.',
            FEAT3_T: 'Privasi terjaga', FEAT3_D: 'Data kesehatan terenkripsi penuh.',
            HOME_ABOUT: 'Nadicare lahir dari pengalaman merawat orang tua yang sering lupa jadwal obat — kami mengubahnya menjadi aplikasi yang kini menemani puluhan ribu keluarga.',
            CHECK1: 'Gratis 14 hari, tanpa kartu kredit.',
            CHECK2: 'Sinkron di semua perangkat.',
            CHECK3: 'Bisa dipakai offline.',
            QUOTE1: 'Jadwal obat ibu saya tidak pernah kelewat lagi sejak pakai ini.',
            QUOTE2: 'Sederhana, ringan, dan benar-benar dipakai setiap hari.',
            QUOTE3: 'Fitur keluarganya juara — saya bisa memantau dari kota lain.',
            CTA_T: 'Mulai kebiasaan sehat hari ini',
            CTA_S: 'Coba gratis 14 hari — batalkan kapan saja.',
            ABOUT_STORY1: 'Nadicare bermula dari kertas tempel jadwal obat di kulkas rumah pendirinya — cara analog yang terlalu sering gagal.',
            ABOUT_STORY2: 'Kini kami tim kecil yang terobsesi pada satu hal: pengingat yang benar-benar diikuti, bukan sekadar berbunyi.',
            VAL1_T: 'Sederhana dulu', VAL1_D: 'Fitur baru boleh masuk hanya bila tidak menambah rumit.',
            VAL2_T: 'Privasi mutlak', VAL2_D: 'Data kesehatanmu bukan barang dagangan.',
            VAL3_T: 'Dengar pengguna', VAL3_D: 'Peta jalan kami disusun dari masukan komunitas.',
            FAQ1_Q: 'Apakah benar-benar gratis 14 hari?', FAQ1_A: 'Ya, tanpa kartu kredit — setelahnya pilih paket atau tetap di versi gratis yang fungsional.',
            FAQ2_Q: 'Data saya disimpan di mana?', FAQ2_A: 'Terenkripsi di server, dan bisa diekspor atau dihapus permanen kapan saja dari pengaturan.',
            FAQ3_Q: 'Bisa untuk berapa anggota keluarga?', FAQ3_A: 'Paket keluarga mencakup hingga 6 profil dalam satu akun.',
            FAQ4_Q: 'Apakah jalan tanpa internet?', FAQ4_A: 'Pengingat tetap berbunyi offline; data tersinkron saat kembali online.',
            CONTACT_SUB: 'Pertanyaan atau masukan? Tim kecil kami membaca semuanya.'
        }
    },
    'Blog / Media': {
        brand: 'Serambi Kata',
        description: 'esai, ulasan, dan cerita tentang budaya, teknologi, dan hidup sehari-hari.',
        recipe: ['hero-editorial', 'about-checks', 'quote-single', 'cta'],
        copy: {
            TAGLINE: 'Bacaan pelan di dunia yang terburu-buru',
            HERO_BADGE: 'Terbit tiap Selasa & Jumat',
            HERO_CTA: 'Mulai Membaca',
            HERO_IMG: 'Artikel pilihan',
            HERO_CARD_T: '600+ tulisan',
            HERO_CARD_S: 'Dari 40+ penulis',
            ABOUT_IMG: 'Meja redaksi',
            STAT1_V: '600+', STAT1_L: 'Tulisan terbit',
            STAT2_V: '40+', STAT2_L: 'Kontributor',
            STAT3_V: '25rb', STAT3_L: 'Pembaca bulanan',
            STAT4_V: '8rb+', STAT4_L: 'Pelanggan nawala',
            FEAT1_T: 'Ditulis serius', FEAT1_D: 'Setiap tulisan melewati penyuntingan berlapis.',
            FEAT2_T: 'Tanpa clickbait', FEAT2_D: 'Judul jujur, isi lebih dalam dari judulnya.',
            FEAT3_T: 'Bebas iklan mengganggu', FEAT3_D: 'Didukung pembaca, bukan pengiklan.',
            HOME_ABOUT: 'Kami percaya masih ada tempat untuk tulisan yang dikerjakan pelan-pelan: diriset, disunting, dan dibaca sampai habis.',
            CHECK1: 'Nawala mingguan berisi kurasi terbaik.',
            CHECK2: 'Arsip terbuka, bisa dibaca kapan saja.',
            CHECK3: 'Terbuka untuk kontributor baru.',
            QUOTE1: 'Satu-satunya nawala yang benar-benar saya tunggu tiap minggu.',
            QUOTE2: 'Tulisannya dalam tapi tetap enak dibaca sambil ngopi.',
            QUOTE3: 'Tempat saya kabur dari linimasa yang bising.',
            CTA_T: 'Jangan lewatkan tulisan baru',
            CTA_S: 'Masuk daftar nawala — gratis, sekali seminggu.',
            ABOUT_STORY1: 'Serambi Kata dimulai sebagai blog pribadi berisi catatan bacaan; pembacanya bertambah, penulisnya ikut bertambah.',
            ABOUT_STORY2: 'Kami tidak mengejar viral. Kami mengejar tulisan yang masih layak dibaca lima tahun lagi.',
            VAL1_T: 'Pelan itu pilihan', VAL1_D: 'Terbit dua kali seminggu, disunting sungguh-sungguh.',
            VAL2_T: 'Jujur pada pembaca', VAL2_D: 'Konten berbayar dan afiliasi selalu ditandai.',
            VAL3_T: 'Ruang untuk suara baru', VAL3_D: 'Separuh rubrik kami diisi kontributor lepas.',
            FAQ1_Q: 'Bagaimana cara mengirim tulisan?', FAQ1_A: 'Kirim draf atau ide lewat halaman kontak — panduan kontributor kami balas bersama tanggapannya.',
            FAQ2_Q: 'Apakah menulis di sini dibayar?', FAQ2_A: 'Ya, setiap tulisan yang terbit mendapat honor — nominalnya tertulis di panduan kontributor.',
            FAQ3_Q: 'Nawalanya berisi apa?', FAQ3_A: 'Kurasi tulisan terbaik minggu itu plus catatan pendek redaksi. Sekali seminggu, tanpa spam.',
            FAQ4_Q: 'Bolehkah menerbitkan ulang tulisan kalian?', FAQ4_A: 'Dengan atribusi dan tautan ke tulisan asli, silakan — kabari kami untuk arsip.',
            CONTACT_SUB: 'Untuk kiriman tulisan, kerja sama, atau sekadar menyapa redaksi.',
            ED_KICKER: 'Esai terbaru',
            ED1_T: 'Mengapa kita lelah scrolling tapi tetap tidak berhenti',
            ED2_T: 'Sepuluh tahun jadi pembaca buku fisik di era layar',
            ED3_T: 'Warung kopi dan hilangnya ruang ketiga di kota kita',
            ED4_T: 'Menulis pelan di internet yang serba cepat'
        }
    },
    'SaaS': {
        brand: 'Kirimin',
        description: 'platform manajemen pengiriman untuk toko online — satu dasbor untuk semua kurir.',
        recipe: ['hero-centered', 'logo-band', 'features', 'pricing-preview', 'quote-single', 'cta'],
        copy: {
            TAGLINE: 'Semua pengiriman, satu dasbor',
            HERO_BADGE: 'Dipakai 2.000+ toko online',
            HERO_CTA: 'Coba Gratis 14 Hari',
            HERO_IMG: 'Dasbor Kirimin',
            HERO_CARD_T: '1 juta+ resi',
            HERO_CARD_S: 'Diproses tiap bulan',
            ABOUT_IMG: 'Tim produk',
            STAT1_V: '2.000+', STAT1_L: 'Toko aktif',
            STAT2_V: '12', STAT2_L: 'Kurir terintegrasi',
            STAT3_V: '1jt+', STAT3_L: 'Resi per bulan',
            STAT4_V: '99,9%', STAT4_L: 'Uptime layanan',
            FEAT1_T: 'Integrasi sekali klik', FEAT1_D: 'Hubungkan marketplace dan kurir dalam hitungan menit.',
            FEAT2_T: 'Otomatisasi resi', FEAT2_D: 'Cetak label dan update status tanpa kerja manual.',
            FEAT3_T: 'Laporan real-time', FEAT3_D: 'Ongkir, keterlambatan, dan retur terpantau jelas.',
            HOME_ABOUT: 'Kirimin dibangun oleh mantan pemilik toko online yang lelah membuka lima dasbor kurir setiap pagi — sekarang cukup satu.',
            CHECK1: 'Tanpa instalasi, jalan di browser.',
            CHECK2: 'Harga per resi, bukan langganan gemuk.',
            CHECK3: 'Dukungan pelanggan manusia, bukan bot.',
            QUOTE1: 'Waktu proses pesanan kami turun dari 3 jam jadi 30 menit.',
            QUOTE2: 'Integrasi marketplace-nya mulus, tim support-nya sigap.',
            QUOTE3: 'Fitur laporannya membuat nego ongkir ke kurir jauh lebih mudah.',
            CTA_T: 'Rasakan bedanya dalam 14 hari',
            CTA_S: 'Gratis penuh — tanpa kartu kredit, tanpa kontrak.',
            ABOUT_STORY1: 'Kirimin lahir dari frustrasi pendirinya sendiri: lima tab dasbor kurir terbuka setiap pagi hanya untuk memproses dua puluh pesanan.',
            ABOUT_STORY2: 'Hari ini lebih dari sejuta resi lewat platform kami tiap bulan — dan lima tab itu tinggal satu.',
            VAL1_T: 'Waktu pengguna itu mahal', VAL1_D: 'Setiap klik yang bisa dihapus, kami hapus.',
            VAL2_T: 'Transparan soal harga', VAL2_D: 'Bayar per resi, tanpa biaya tersembunyi.',
            VAL3_T: 'Andal itu wajib', VAL3_D: 'Toko Anda tidak libur; server kami juga tidak.',
            FAQ1_Q: 'Kurir apa saja yang terintegrasi?', FAQ1_A: 'Dua belas kurir utama nasional — daftar lengkapnya di halaman fitur, dan terus bertambah.',
            FAQ2_Q: 'Bagaimana skema harganya?', FAQ2_A: 'Bayar per resi yang diproses. Tanpa biaya bulanan minimum, tanpa kontrak tahunan.',
            FAQ3_Q: 'Apakah data toko saya aman?', FAQ3_A: 'Terenkripsi saat transit dan tersimpan; kami tidak pernah menjual data transaksi.',
            FAQ4_Q: 'Bagaimana jika butuh bantuan?', FAQ4_A: 'Tim support manusia tersedia di jam operasional lewat chat — rata-rata balas di bawah 5 menit.',
            CONTACT_SUB: 'Butuh demo untuk tim Anda? Jadwalkan lewat formulir ini.',
            LOGOS_T: 'Dipakai ribuan toko online',
            LOGO1: 'Lokalane', LOGO2: 'Toko Delapan', LOGO3: 'Rumah Modest', LOGO4: 'Gaya Living', LOGO5: 'Kopi Anara',
            PLAN_S: 'Bayar per resi — paket berlangganan untuk volume besar.',
            PLAN1_N: 'Rintisan', PLAN1_P: 'Rp0', PLAN1_D: 'Sampai 50 resi/bulan, semua kurir, tanpa kartu kredit.',
            PLAN2_N: 'Bertumbuh', PLAN2_P: 'Rp149rb', PLAN2_D: 'Sampai 1.000 resi/bulan plus otomasi dan laporan.',
            PLAN3_N: 'Skala', PLAN3_P: 'Rp499rb', PLAN3_D: 'Resi tanpa batas, multi-gudang, dan dukungan prioritas.'
        }
    },
    'Pendidikan / Kursus': {
        brand: 'Akademi Cakap',
        description: 'kursus keterampilan digital dengan mentor praktisi dan kelas kecil.',
        recipe: ['hero-split', 'stats', 'product-strip', 'steps', 'quotes-trio', 'cta'],
        copy: {
            TAGLINE: 'Belajar langsung dari praktisinya',
            HERO_BADGE: 'Angkatan baru dibuka tiap bulan',
            HERO_CTA: 'Lihat Jadwal Kelas',
            HERO_IMG: 'Suasana kelas',
            HERO_CARD_T: '3.500+ alumni',
            HERO_CARD_S: '78% naik karier dalam setahun',
            ABOUT_IMG: 'Mentor kami',
            STAT1_V: '3.500+', STAT1_L: 'Alumni',
            STAT2_V: '24', STAT2_L: 'Program kursus',
            STAT3_V: '60+', STAT3_L: 'Mentor praktisi',
            STAT4_V: '78%', STAT4_L: 'Alumni naik karier',
            FEAT1_T: 'Kelas kecil', FEAT1_D: 'Maksimal 20 peserta agar semua kebagian bimbingan.',
            FEAT2_T: 'Kurikulum industri', FEAT2_D: 'Disusun bareng perusahaan yang merekrut.',
            FEAT3_T: 'Portofolio nyata', FEAT3_D: 'Lulus membawa karya, bukan cuma sertifikat.',
            HOME_ABOUT: 'Kami memulai dari satu kelas desain berisi 12 orang di sebuah coworking space; kini ribuan alumni kami bekerja di perusahaan yang dulu hanya mereka impikan.',
            CHECK1: 'Bisa dicicil, ada beasiswa tiap angkatan.',
            CHECK2: 'Rekaman kelas bisa diakses selamanya.',
            CHECK3: 'Komunitas alumni yang saling membuka pintu.',
            QUOTE1: 'Tiga bulan setelah lulus, saya diterima sebagai desainer di startup.',
            QUOTE2: 'Mentornya praktisi beneran, studi kasusnya dipakai kerja sehari-hari.',
            QUOTE3: 'Kelas kecilnya bikin berani bertanya — beda dari kursus online biasa.',
            CTA_T: 'Angkatan baru segera dimulai',
            CTA_S: 'Kuota terbatas — amankan kursimu sekarang.',
            ABOUT_STORY1: 'Akademi Cakap dimulai dari satu kelas desain berisi 12 orang; sebagian besar pesertanya kini justru menjadi mentor kami.',
            ABOUT_STORY2: 'Kurikulum kami ditinjau tiap semester bersama perusahaan perekrut — yang diajarkan adalah yang benar-benar dipakai bekerja.',
            VAL1_T: 'Praktik di atas teori', VAL1_D: 'Tugasnya studi kasus nyata, bukan soal pilihan ganda.',
            VAL2_T: 'Tidak meninggalkan siapa pun', VAL2_D: 'Kelas kecil supaya yang tertinggal ketahuan cepat.',
            VAL3_T: 'Jujur soal hasil', VAL3_D: 'Statistik alumni kami publikasikan apa adanya.',
            FAQ1_Q: 'Apakah cocok untuk pemula total?', FAQ1_A: 'Ya — jalur pemula dimulai dari nol, dan tes penempatan membantu memilih kelas yang pas.',
            FAQ2_Q: 'Bagaimana skema pembayarannya?', FAQ2_A: 'Bisa lunas atau dicicil 3–6 kali; ada beasiswa penuh tiap angkatan untuk yang membutuhkan.',
            FAQ3_Q: 'Berapa lama satu program?', FAQ3_A: '8–16 minggu tergantung program, 2–3 sesi live per minggu plus tugas mandiri.',
            FAQ4_Q: 'Apakah ada bantuan penyaluran kerja?', FAQ4_A: 'Ada — review CV, simulasi wawancara, dan kanal lowongan khusus alumni.',
            CONTACT_SUB: 'Bingung pilih program? Konsultasi dulu, gratis.',
            CARD_WORD: 'Kelas',
            STRIP_T: 'Program populer',
            STRIP_S: 'Kelas dengan angkatan yang paling cepat penuh.',
            STEPS_T: 'Cara mendaftar',
            STEP1_T: 'Ikut tes penempatan', STEP1_D: 'Gratis 15 menit — supaya mulai dari level yang pas.',
            STEP2_T: 'Pilih kelas & jadwal', STEP2_D: 'Sesuaikan dengan ritme harianmu, malam atau akhir pekan.',
            STEP3_T: 'Mulai belajar', STEP3_D: 'Kelas live, tugas nyata, dan mentor yang menemani.',
            CATALOG_SUB: 'Program yang sedang buka pendaftaran.',
            CARD_META: '4,8 · 300+ alumni',
            CARD_DESC: 'Kelas live dengan mentor praktisi dan proyek portofolio.',
            CARD_PRICE: 'Rp2.500.000',
            CARD_CTA: 'Detail'
        }
    },
    'Kesehatan / Klinik': {
        brand: 'Klinik Amerta',
        description: 'klinik keluarga dengan dokter tetap, janji temu tepat waktu, dan rekam medis digital.',
        recipe: ['hero-split', 'steps', 'stats', 'quotes-trio', 'cta'],
        copy: {
            TAGLINE: 'Perawatan keluarga yang tenang dan tepat waktu',
            HERO_BADGE: 'Terakreditasi & BPJS',
            HERO_CTA: 'Buat Janji Temu',
            HERO_IMG: 'Ruang periksa',
            HERO_CARD_T: 'Sejak 2010',
            HERO_CARD_S: 'Melayani 3 generasi pasien',
            ABOUT_IMG: 'Tim medis',
            STAT1_V: '15', STAT1_L: 'Tahun melayani',
            STAT2_V: '9', STAT2_L: 'Dokter tetap',
            STAT3_V: '40rb+', STAT3_L: 'Pasien terdaftar',
            STAT4_V: '<15 mnt', STAT4_L: 'Rata-rata tunggu',
            FEAT1_T: 'Janji temu online', FEAT1_D: 'Pilih dokter dan jam, datang tanpa antre panjang.',
            FEAT2_T: 'Dokter keluarga tetap', FEAT2_D: 'Riwayat Anda dipahami, bukan diulang dari nol.',
            FEAT3_T: 'Rekam medis digital', FEAT3_D: 'Hasil lab dan resep tersimpan rapi, bisa diakses.',
            HOME_ABOUT: 'Amerta berdiri dengan satu prinsip: pasien bukan nomor antrean. Dokter kami mengenal pasiennya, dan sistem kami memastikan waktu Anda dihargai.',
            CHECK1: 'Melayani BPJS dan asuransi swasta.',
            CHECK2: 'Buka hingga malam di hari kerja.',
            CHECK3: 'Apotek dan lab di satu gedung.',
            QUOTE1: 'Anak saya tidak takut ke dokter lagi — dokternya sabar sekali.',
            QUOTE2: 'Booking dari HP, datang langsung dipanggil. Begini seharusnya klinik.',
            QUOTE3: 'Riwayat berobat keluarga tersimpan rapi, pindah dokter pun mulus.',
            CTA_T: 'Jangan tunda kesehatan Anda',
            CTA_S: 'Jadwalkan pemeriksaan hari ini — slot malam tersedia.',
            ABOUT_STORY1: 'Amerta dibuka tahun 2010 oleh dua dokter keluarga yang ingin praktik dengan cara berbeda: waktu konsultasi yang cukup dan pasien yang dikenal namanya.',
            ABOUT_STORY2: 'Prinsip itu tidak berubah meski kami tumbuh — dokter tetap, rekam medis tersambung, dan jadwal yang dihormati.',
            VAL1_T: 'Pasien bukan nomor', VAL1_D: 'Konsultasi tidak diburu-buru; pertanyaan Anda dijawab tuntas.',
            VAL2_T: 'Berbasis bukti', VAL2_D: 'Diagnosis dan resep mengikuti panduan klinis terkini.',
            VAL3_T: 'Terjangkau dan jelas', VAL3_D: 'Estimasi biaya disampaikan sebelum tindakan.',
            SVC1_T: 'Pemeriksaan Umum', SVC1_D: 'Konsultasi dokter umum untuk keluhan harian dan rujukan bila diperlukan.',
            SVC2_T: 'Medical Check-Up', SVC2_D: 'Paket pemeriksaan berkala dengan hasil lab di hari yang sama.',
            SVC3_T: 'Kesehatan Anak & Vaksinasi', SVC3_D: 'Imunisasi lengkap dan tumbuh kembang dengan dokter yang sabar.',
            FAQ1_Q: 'Apakah menerima BPJS?', FAQ1_A: 'Ya, untuk layanan yang tercakup — bawa kartu dan KTP saat berkunjung.',
            FAQ2_Q: 'Bagaimana cara membuat janji temu?', FAQ2_A: 'Lewat halaman Janji Temu atau WhatsApp; pilih dokter dan jam yang tersedia.',
            FAQ3_Q: 'Apakah melayani pasien tanpa janji?', FAQ3_A: 'Melayani, namun pasien dengan janji diprioritaskan — daftar online lebih pasti.',
            FAQ4_Q: 'Bisakah melihat hasil lab secara online?', FAQ4_A: 'Bisa — hasil dikirim ke akun pasien dan bisa diunduh kapan saja.',
            CONTACT_SUB: 'Untuk janji temu, hasil lab, atau pertanyaan layanan.',
            STEPS_T: 'Alur berobat di Amerta',
            STEP1_T: 'Buat janji temu', STEP1_D: 'Pilih dokter dan jam lewat halaman Janji Temu atau WhatsApp.',
            STEP2_T: 'Datang tanpa antre', STEP2_D: 'Check-in dengan kode booking — rekam medis Anda sudah siap.',
            STEP3_T: 'Konsultasi & tindak lanjut', STEP3_D: 'Resep, hasil lab, dan jadwal kontrol terkirim ke akun Anda.',
            CATALOG_SUB: 'Dokter kami — pilih dan buat janji temu.',
            CARD_META: 'Dokter Umum · SIP aktif',
            CARD_DESC: 'Praktik Senin–Sabtu, menerima BPJS dan asuransi.',
            CARD_PRICE: 'Jadwal hari ini',
            CARD_CTA: 'Buat Janji'
        }
    },
    'Restoran / Kuliner': {
        brand: 'Dapur Laras',
        description: 'masakan rumahan Nusantara dengan bahan segar dari pasar pagi.',
        recipe: ['hero-visual', 'menu-highlight', 'about-checks', 'quote-single', 'cta'],
        copy: {
            TAGLINE: 'Rasa rumah, di meja Anda',
            HERO_BADGE: 'Buka setiap hari 10.00–22.00',
            HERO_CTA: 'Reservasi Meja',
            HERO_IMG: 'Hidangan andalan',
            HERO_CARD_T: 'Resep turun-temurun',
            HERO_CARD_S: 'Sejak dapur nenek, 1987',
            ABOUT_IMG: 'Dapur kami',
            STAT1_V: '38', STAT1_L: 'Menu Nusantara',
            STAT2_V: '4,9', STAT2_L: 'Rating pengunjung',
            STAT3_V: '200+', STAT3_L: 'Porsi per hari',
            STAT4_V: '100%', STAT4_L: 'Bahan segar harian',
            FEAT1_T: 'Belanja tiap pagi', FEAT1_D: 'Bumbu dan sayur dibeli segar, bukan stok beku.',
            FEAT2_T: 'Dimasak saat dipesan', FEAT2_D: 'Setiap piring keluar panas dari wajan.',
            FEAT3_T: 'Ramah keluarga', FEAT3_D: 'Ruang lesehan dan menu anak tersedia.',
            HOME_ABOUT: 'Dapur Laras meneruskan resep nenek yang dulu hanya dimasak saat kumpul keluarga — kini kami menyajikannya setiap hari, dengan cara yang sama: sabar dan tanpa penyedap berlebihan.',
            CHECK1: 'Tanpa MSG berlebih, rasa dari kaldu asli.',
            CHECK2: 'Menerima pesanan nasi kotak dan tumpeng.',
            CHECK3: 'Parkir luas, musala tersedia.',
            QUOTE1: 'Gulainya seperti masakan ibu di kampung. Nagih.',
            QUOTE2: 'Tempatnya nyaman buat keluarga, pelayanannya cepat.',
            QUOTE3: 'Pesan tumpeng untuk kantor, semua kolega bertanya belinya di mana.',
            CTA_T: 'Lapar? Meja Anda menunggu',
            CTA_S: 'Reservasi lewat WhatsApp — balasan dalam 5 menit.',
            ABOUT_STORY1: 'Dapur Laras berawal dari dapur nenek yang hanya menyala saat kumpul keluarga; resep-resepnya kami selamatkan satu per satu dari buku catatan yang mulai pudar.',
            ABOUT_STORY2: 'Semua masih dikerjakan dengan cara lama — bumbu diulek, kaldu direbus berjam-jam — karena rasa memang tidak bisa terburu-buru.',
            VAL1_T: 'Segar setiap pagi', VAL1_D: 'Belanja bahan sendiri ke pasar, setiap hari.',
            VAL2_T: 'Setia pada resep', VAL2_D: 'Rasa yang sama sejak hari pertama buka.',
            VAL3_T: 'Rumah untuk semua', VAL3_D: 'Anak kecil sampai kakek-nenek betah di sini.',
            FAQ1_Q: 'Apakah perlu reservasi?', FAQ1_A: 'Akhir pekan dan jam makan malam sebaiknya reservasi — hari biasa umumnya langsung dapat meja.',
            FAQ2_Q: 'Apakah melayani pesan antar?', FAQ2_A: 'Ya, lewat WhatsApp atau aplikasi ojek online untuk radius 5 km.',
            FAQ3_Q: 'Menerima pesanan nasi kotak?', FAQ3_A: 'Menerima, minimal H-1 untuk di bawah 50 kotak dan H-3 untuk di atasnya.',
            FAQ4_Q: 'Adakah pilihan tanpa daging?', FAQ4_A: 'Ada — sayur dan lauk nabati tersedia setiap hari, tinggal sebut saat memesan.',
            CONTACT_SUB: 'Reservasi, pesan antar, atau tanya menu hari ini.',
            MENU_T: 'Andalan dapur kami',
            MENU1_N: 'Gudeg Komplit Laras', MENU1_D: 'Gudeg manis legit dengan krecek, telur, dan ayam kampung.', MENU1_P: 'Rp38.000',
            MENU2_N: 'Rawon Iga Api Kecil', MENU2_D: 'Kuah kluwek pekat, iga empuk direbus lima jam.', MENU2_P: 'Rp52.000',
            MENU3_N: 'Pecel Pincuk Pasar Pagi', MENU3_D: 'Sayur segar pagi itu dengan sambal kacang tumbuk kasar.', MENU3_P: 'Rp24.000',
            MENU4_N: 'Wedang Uwuh Rempah', MENU4_D: 'Racikan jahe, secang, dan rempah hangat khas rumah.', MENU4_P: 'Rp15.000'
        }
    },
    'Properti / Real Estate': {
        brand: 'Griya Antara',
        description: 'agen properti terpercaya untuk jual, beli, dan sewa rumah di kota Anda.',
        recipe: ['hero-split', 'product-strip', 'stats', 'features', 'cta'],
        copy: {
            TAGLINE: 'Temukan rumah yang terasa seperti pulang',
            HERO_BADGE: 'Agen berlisensi resmi',
            HERO_CTA: 'Jadwalkan Survei',
            HERO_IMG: 'Listing unggulan',
            HERO_CARD_T: '500+ transaksi',
            HERO_CARD_S: 'Senilai ratusan miliar rupiah',
            ABOUT_IMG: 'Tim agen kami',
            STAT1_V: '500+', STAT1_L: 'Transaksi sukses',
            STAT2_V: '300+', STAT2_L: 'Listing aktif',
            STAT3_V: '30', STAT3_L: 'Agen berlisensi',
            STAT4_V: '45 hari', STAT4_L: 'Rata-rata terjual',
            FEAT1_T: 'Harga pasar akurat', FEAT1_D: 'Valuasi berbasis data transaksi, bukan perasaan.',
            FEAT2_T: 'Legal dikawal', FEAT2_D: 'Sertifikat dan akta diperiksa notaris rekanan.',
            FEAT3_T: 'Foto & tur virtual', FEAT3_D: 'Lihat detail rumah sebelum meluangkan waktu survei.',
            HOME_ABOUT: 'Kami memulai sebagai kantor kecil dengan tiga agen dan satu prinsip: jujur soal kondisi properti. Prinsip itu yang membuat klien kami datang dari rekomendasi mulut ke mulut.',
            CHECK1: 'Tanpa biaya tersembunyi — komisi jelas di awal.',
            CHECK2: 'Pendampingan KPR sampai akad.',
            CHECK3: 'Listing diverifikasi langsung oleh tim.',
            QUOTE1: 'Rumah kami laku dalam sebulan, di harga yang masuk akal.',
            QUOTE2: 'Diantar survei sabar sekali sampai ketemu yang cocok.',
            QUOTE3: 'Urusan KPR yang rumit jadi terasa gampang karena dikawal.',
            CTA_T: 'Mau jual atau cari rumah?',
            CTA_S: 'Konsultasi gratis dengan agen berlisensi kami.',
            ABOUT_STORY1: 'Griya Antara dimulai dari tiga agen dan satu ruko kecil, dengan aturan yang saat itu dianggap aneh: kondisi properti diceritakan apa adanya, termasuk kekurangannya.',
            ABOUT_STORY2: 'Aturan aneh itu terbukti benar — sebagian besar klien kami datang dari rekomendasi klien sebelumnya.',
            VAL1_T: 'Jujur soal kondisi', VAL1_D: 'Kekurangan properti disebutkan sebelum Anda jatuh hati.',
            VAL2_T: 'Data, bukan gimmick', VAL2_D: 'Valuasi dari transaksi pembanding yang nyata.',
            VAL3_T: 'Aman secara hukum', VAL3_D: 'Legalitas dicek notaris sebelum tanda tangan apa pun.',
            FAQ1_Q: 'Berapa komisi agennya?', FAQ1_A: 'Standar dan tertulis di perjanjian sejak awal — tidak ada biaya tersembunyi.',
            FAQ2_Q: 'Berapa lama properti biasanya terjual?', FAQ2_A: 'Rata-rata 45 hari untuk harga yang sesuai pasar; valuasi kami bantu tetapkan di awal.',
            FAQ3_Q: 'Apakah membantu pengurusan KPR?', FAQ3_A: 'Ya, kami dampingi dari simulasi, pengajuan ke beberapa bank, sampai akad.',
            FAQ4_Q: 'Bisakah titip jual sambil tetap ditempati?', FAQ4_A: 'Bisa — jadwal kunjungan diatur dengan persetujuan Anda.',
            CONTACT_SUB: 'Ceritakan properti yang Anda cari atau ingin jual.',
            CARD_WORD: 'Properti',
            STRIP_T: 'Listing pilihan minggu ini',
            STRIP_S: 'Properti terverifikasi dengan harga sesuai pasar.',
            CATALOG_SUB: 'Listing terverifikasi, foto sesuai kondisi asli.',
            CARD_META: 'SHM · LT 120 m²',
            CARD_DESC: 'Rumah 2 lantai, 3 kamar, dekat akses tol dan sekolah.',
            CARD_PRICE: 'Rp850 juta',
            CARD_CTA: 'Detail'
        }
    },
    'Travel / Wisata': {
        brand: 'Langkah Nusantara',
        description: 'open trip dan private tour ke destinasi terbaik Indonesia bersama pemandu lokal.',
        recipe: ['hero-visual', 'product-strip', 'steps', 'quote-single', 'cta'],
        copy: {
            TAGLINE: 'Jelajahi Indonesia bersama orang yang paling mengenalnya',
            HERO_BADGE: 'Berizin resmi & berasuransi',
            HERO_CTA: 'Lihat Paket Wisata',
            HERO_IMG: 'Destinasi favorit',
            HERO_CARD_T: '15rb+ peserta',
            HERO_CARD_S: 'Pulang membawa cerita',
            ABOUT_IMG: 'Pemandu lokal kami',
            STAT1_V: '60+', STAT1_L: 'Destinasi',
            STAT2_V: '15rb+', STAT2_L: 'Peserta trip',
            STAT3_V: '100%', STAT3_L: 'Pemandu lokal',
            STAT4_V: '4,9', STAT4_L: 'Rating perjalanan',
            FEAT1_T: 'Pemandu lokal asli', FEAT1_D: 'Yang tahu jalan tikus dan cerita di baliknya.',
            FEAT2_T: 'Grup kecil', FEAT2_D: 'Maksimal 12 orang — santai, bukan rombongan bus.',
            FEAT3_T: 'Harga transparan', FEAT3_D: 'Semua biaya tertulis, tanpa tagihan kejutan.',
            HOME_ABOUT: 'Berawal dari hobi mengantar teman keliling kampung halaman, kami tumbuh menjadi jaringan pemandu lokal di puluhan destinasi — dengan janji yang sama: wisata yang menghidupi warga setempat.',
            CHECK1: 'Asuransi perjalanan untuk semua peserta.',
            CHECK2: 'Bebas reschedule hingga H-7.',
            CHECK3: 'Sebagian keuntungan kembali ke desa wisata.',
            QUOTE1: 'Rasanya seperti diajak jalan saudara, bukan ikut tur.',
            QUOTE2: 'Itinerary-nya manusiawi, tidak dikejar-kejar waktu.',
            QUOTE3: 'Spot yang dikunjungi bukan yang pasaran. Foto-fotonya juara.',
            CTA_T: 'Kapan terakhir kamu benar-benar libur?',
            CTA_S: 'Kursi trip bulan ini tinggal sedikit — cek jadwalnya.',
            ABOUT_STORY1: 'Langkah Nusantara berawal dari kebiasaan mengantar teman keliling kampung halaman — sampai teman-temannya teman ikut minta diantar.',
            ABOUT_STORY2: 'Kini kami jaringan pemandu lokal di puluhan destinasi, dan prinsipnya tetap: yang paling tahu suatu tempat adalah orang yang tinggal di sana.',
            VAL1_T: 'Lokal sampai akar', VAL1_D: 'Pemandu, penginapan, dan warung — semuanya warga setempat.',
            VAL2_T: 'Kecil dan santai', VAL2_D: 'Grup maksimal 12 — perjalanan, bukan penggiringan.',
            VAL3_T: 'Bertanggung jawab', VAL3_D: 'Sampah dibawa turun, alam ditinggalkan seperti semula.',
            FAQ1_Q: 'Apa saja yang termasuk harga paket?', FAQ1_A: 'Transportasi lokal, penginapan, makan sesuai itinerary, tiket masuk, pemandu, dan asuransi — rinciannya di tiap paket.',
            FAQ2_Q: 'Bagaimana kalau saya berangkat sendirian?', FAQ2_A: 'Justru banyak peserta kami solo traveler — open trip cara paling enak dapat teman jalan.',
            FAQ3_Q: 'Bisakah reschedule atau refund?', FAQ3_A: 'Reschedule gratis hingga H-7; refund mengikuti ketentuan tiap paket, tertulis jelas.',
            FAQ4_Q: 'Apakah aman untuk pemula?', FAQ4_A: 'Tiap paket punya level kesulitan; pemandu kami bersertifikat P3K dan rutenya teruji.',
            CONTACT_SUB: 'Tanya jadwal, kustomisasi rute, atau private trip.',
            CARD_WORD: 'Trip',
            STRIP_T: 'Trip keberangkatan terdekat',
            STRIP_S: 'Kursi terbatas — grup kecil maksimal 12 orang.',
            STEPS_T: 'Cara ikut trip',
            STEP1_T: 'Pilih paket & tanggal', STEP1_D: 'Cek itinerary lengkap dan tanggal keberangkatan yang tersedia.',
            STEP2_T: 'Bayar uang muka', STEP2_D: 'Kursi terkunci dengan DP 30% — pelunasan H-7 keberangkatan.',
            STEP3_T: 'Berangkat!', STEP3_D: 'Grup WhatsApp dibuka H-5; pemandu menjemput di titik kumpul.',
            CATALOG_SUB: 'Jadwal keberangkatan terdekat — kursi terbatas.',
            CARD_META: '4,9 · 3 hari 2 malam',
            CARD_DESC: 'Termasuk penginapan, makan, pemandu lokal, dan asuransi.',
            CARD_PRICE: 'Rp1.850.000',
            CARD_CTA: 'Lihat Paket'
        }
    },
    'Event / Acara': {
        brand: 'Svara Fest',
        description: 'festival musik dan kreativitas dua hari — panggung lintas genre, pasar kreatif, dan lokakarya.',
        recipe: ['hero-centered', 'stats', 'product-strip', 'quote-single', 'cta'],
        copy: {
            TAGLINE: 'Dua hari, tiga panggung, satu pengalaman',
            HERO_BADGE: '14–15 November 2026 • Bandung',
            HERO_CTA: 'Beli Tiket',
            HERO_IMG: 'Panggung utama',
            HERO_CARD_T: 'Edisi ke-5',
            HERO_CARD_S: 'Tahun lalu sold out',
            ABOUT_IMG: 'Keseruan tahun lalu',
            STAT1_V: '30+', STAT1_L: 'Penampil',
            STAT2_V: '3', STAT2_L: 'Panggung',
            STAT3_V: '12rb', STAT3_L: 'Pengunjung tahun lalu',
            STAT4_V: '40+', STAT4_L: 'Tenant kreatif',
            FEAT1_T: 'Lineup lintas genre', FEAT1_D: 'Dari folk akustik sampai elektronik — semua kebagian.',
            FEAT2_T: 'Bukan cuma musik', FEAT2_D: 'Pasar kreatif, lokakarya, dan pameran seni.',
            FEAT3_T: 'Nyaman seharian', FEAT3_D: 'Area istirahat, food court, dan akses difabel.',
            HOME_ABOUT: 'Svara lahir dari kolektif musisi independen yang ingin panggung untuk semua genre. Lima tahun kemudian, festival ini menjadi ruang temu ribuan pecinta musik dan pelaku kreatif.',
            CHECK1: 'Tiket termasuk akses semua panggung.',
            CHECK2: 'Anak di bawah 10 tahun gratis.',
            CHECK3: 'Refund penuh bila acara batal.',
            QUOTE1: 'Kurasi penampilnya selalu berani dan segar tiap tahun.',
            QUOTE2: 'Festival paling tertata yang pernah saya datangi.',
            QUOTE3: 'Datang untuk musiknya, pulang bawa banyak barang dari pasar kreatifnya.',
            CTA_T: 'Jangan sampai kehabisan lagi',
            CTA_S: 'Presale II berakhir minggu ini — harga naik setelahnya.',
            ABOUT_STORY1: 'Svara dimulai sebagai gigs kolektif di halaman belakang sebuah kafe — 200 penonton, satu panggung pinjaman, dan listrik yang dua kali padam.',
            ABOUT_STORY2: 'Lima edisi kemudian, semangatnya tidak berubah: panggung yang adil untuk semua genre dan ruang bagi pelaku kreatif lokal.',
            VAL1_T: 'Kurasi berani', VAL1_D: 'Line-up dipilih kualitasnya, bukan sekadar nama besar.',
            VAL2_T: 'Nyaman untuk semua', VAL2_D: 'Akses difabel, ruang laktasi, dan air minum gratis.',
            VAL3_T: 'Panggung yang adil', VAL3_D: 'Musisi lokal dibayar layak, bukan "dibayar exposure".',
            FAQ1_Q: 'Di mana dan kapan acaranya?', FAQ1_A: '14–15 November 2026 di Bandung — detail venue dan peta akses ada di halaman jadwal.',
            FAQ2_Q: 'Bagaimana cara membeli tiket?', FAQ2_A: 'Lewat halaman tiket resmi; e-ticket dikirim ke email dan dipindai di gerbang.',
            FAQ3_Q: 'Apakah tiket bisa refund?', FAQ3_A: 'Refund penuh bila acara batal; perpindahan nama diperbolehkan hingga H-3.',
            FAQ4_Q: 'Apa yang boleh dibawa masuk?', FAQ4_A: 'Botol minum kosong boleh; kamera profesional dan minuman luar tidak — daftar lengkap di FAQ tiket.',
            CONTACT_SUB: 'Pertanyaan tiket, media, atau kemitraan sponsor.',
            CARD_WORD: 'Penampil',
            STRIP_T: 'Sorotan line-up',
            STRIP_S: 'Sebagian penampil edisi tahun ini — daftar lengkap di halaman jadwal.',
            CATALOG_SUB: 'Jadwal panggung dan penampil edisi tahun ini.',
            CARD_META: 'Panggung Utama · 20.00',
            CARD_DESC: 'Penampilan spesial dengan aransemen khusus festival.',
            CARD_PRICE: 'Hari ke-1',
            CARD_CTA: 'Detail'
        }
    },
    'Nonprofit / Komunitas': {
        brand: 'Yayasan Pelita Baca',
        description: 'gerakan literasi yang membangun taman baca dan melatih relawan di pelosok Indonesia.',
        recipe: ['hero-split', 'stats', 'about-checks', 'quote-single', 'cta'],
        copy: {
            TAGLINE: 'Satu buku bisa mengubah arah hidup anak',
            HERO_BADGE: 'Yayasan terdaftar resmi',
            HERO_CTA: 'Donasi Sekarang',
            HERO_IMG: 'Taman baca kami',
            HERO_CARD_T: '52 taman baca',
            HERO_CARD_S: 'Di 17 provinsi',
            ABOUT_IMG: 'Relawan kami',
            STAT1_V: '52', STAT1_L: 'Taman baca berdiri',
            STAT2_V: '17', STAT2_L: 'Provinsi terjangkau',
            STAT3_V: '9rb+', STAT3_L: 'Anak terlayani',
            STAT4_V: '800+', STAT4_L: 'Relawan aktif',
            FEAT1_T: 'Transparan penuh', FEAT1_D: 'Laporan keuangan diaudit dan dipublikasikan.',
            FEAT2_T: 'Berkelanjutan', FEAT2_D: 'Taman baca dikelola warga, bukan proyek sekali jadi.',
            FEAT3_T: 'Mudah terlibat', FEAT3_D: 'Donasi buku, dana, atau waktu — semua berarti.',
            HOME_ABOUT: 'Bermula dari satu rak buku di teras rumah, gerakan ini tumbuh menjadi jaringan taman baca yang dikelola warga — karena kami percaya akses bacaan adalah hak semua anak.',
            CHECK1: '100% donasi publik untuk program.',
            CHECK2: 'Laporan dampak dikirim ke donatur tiap kuartal.',
            CHECK3: 'Kunjungi taman baca kami kapan saja.',
            QUOTE1: 'Anak-anak di desa kami sekarang antre pinjam buku, bukan gadget.',
            QUOTE2: 'Donasi terasa nyata karena laporannya detail dan jujur.',
            QUOTE3: 'Jadi relawan di sini adalah keputusan terbaik saya tahun ini.',
            CTA_T: 'Ikut nyalakan pelita',
            CTA_S: 'Mulai dari Rp50.000 — atau donasikan buku layak baca.',
            ABOUT_STORY1: 'Pelita Baca bermula dari satu rak buku di teras rumah relawan pertama kami — anak-anak tetangga datang, lalu tidak berhenti datang.',
            ABOUT_STORY2: 'Model kami sederhana dan terbukti: warga yang mengelola, kami yang memasok buku, pelatihan, dan pendampingan.',
            VAL1_T: 'Transparan total', VAL1_D: 'Laporan keuangan diaudit dan terbuka untuk publik.',
            VAL2_T: 'Milik warga', VAL2_D: 'Taman baca dikelola komunitas, bukan kantor pusat.',
            VAL3_T: 'Jangka panjang', VAL3_D: 'Kami menetap dan mendampingi, bukan seremoni peresmian.',
            FAQ1_Q: 'Ke mana donasi saya disalurkan?', FAQ1_A: '100% donasi publik untuk program: buku, rak, pelatihan relawan, dan operasional taman baca.',
            FAQ2_Q: 'Bisakah donasi buku bekas?', FAQ2_A: 'Bisa — buku anak dan remaja layak baca; alamat pengiriman ada di halaman donasi.',
            FAQ3_Q: 'Bagaimana menjadi relawan?', FAQ3_A: 'Isi formulir di halaman program; pelatihan dasar diadakan tiap bulan, daring dan luring.',
            FAQ4_Q: 'Apakah donasi dapat bukti resmi?', FAQ4_A: 'Ya, kwitansi resmi yayasan dikirim otomatis ke email Anda.',
            CONTACT_SUB: 'Untuk donasi, relawan, atau kemitraan CSR.',
            CATALOG_SUB: 'Program yang sedang berjalan dan cara terlibat.',
            CARD_META: 'Berjalan · 17 provinsi',
            CARD_DESC: 'Program pendirian dan pendampingan taman baca warga.',
            CARD_PRICE: 'Terbuka',
            CARD_CTA: 'Ikut Serta'
        }
    },
    'Personal': {
        brand: 'Raka Mahendra',
        description: 'penulis dan pengembang perangkat lunak — menulis tentang teknologi, produktivitas, dan hidup yang disengaja.',
        recipe: ['hero-minimal', 'about-checks', 'quote-single', 'cta'],
        copy: {
            TAGLINE: 'Halo, saya Raka — saya membangun dan menulis',
            HERO_BADGE: 'Software engineer & penulis',
            HERO_CTA: 'Hubungi Saya',
            HERO_IMG: 'Potret diri',
            HERO_CARD_T: '10 tahun',
            HERO_CARD_S: 'Membangun produk digital',
            ABOUT_IMG: 'Ruang kerja saya',
            STAT1_V: '10+', STAT1_L: 'Tahun berkarier',
            STAT2_V: '120+', STAT2_L: 'Tulisan terbit',
            STAT3_V: '6', STAT3_L: 'Produk diluncurkan',
            STAT4_V: '3', STAT4_L: 'Kali jadi pembicara',
            FEAT1_T: 'Menulis rutin', FEAT1_D: 'Esai mingguan tentang teknologi dan kebiasaan.',
            FEAT2_T: 'Membangun terbuka', FEAT2_D: 'Proyek sampingan didokumentasikan apa adanya.',
            FEAT3_T: 'Berbagi lewat mentoring', FEAT3_D: 'Sesi 1-on-1 untuk developer pemula tiap bulan.',
            HOME_ABOUT: 'Sepuluh tahun bekerja di industri teknologi mengajari saya satu hal: hal rumit menjadi jelas ketika dituliskan. Situs ini adalah tempat saya menuliskannya.',
            CHECK1: 'Terbuka untuk proyek lepas terpilih.',
            CHECK2: 'Nawala tanpa spam, sebulan dua kali.',
            CHECK3: 'Slot mentoring gratis tiap awal bulan.',
            QUOTE1: 'Tulisannya membantu saya lulus wawancara kerja pertama sebagai developer.',
            QUOTE2: 'Kolaborator yang rapi, komunikatif, dan tepat waktu.',
            QUOTE3: 'Sesi mentoringnya to the point dan membuka wawasan.',
            CTA_T: 'Mari terhubung',
            CTA_S: 'Untuk kolaborasi, undangan bicara, atau sekadar menyapa.',
            ABOUT_STORY1: 'Sepuluh tahun lalu saya menulis baris kode profesional pertama; lima tahun kemudian saya sadar menulis kalimat sama pentingnya dengan menulis kode.',
            ABOUT_STORY2: 'Situs ini adalah taman digital saya: esai, catatan proyek, dan hal-hal yang saya harap saya tahu lebih awal.',
            VAL1_T: 'Belajar di tempat terbuka', VAL1_D: 'Proses dan kegagalan didokumentasikan, bukan cuma hasil.',
            VAL2_T: 'Sederhana itu mahal', VAL2_D: 'Solusi terbaik biasanya yang paling sedikit bergerak.',
            VAL3_T: 'Angkat yang lain', VAL3_D: 'Ilmu bertambah justru saat dibagikan.',
            FAQ1_Q: 'Apakah menerima proyek lepas?', FAQ1_A: 'Terbuka untuk proyek terpilih yang cocok dengan keahlian saya — ceritakan lewat halaman kontak.',
            FAQ2_Q: 'Bagaimana ikut sesi mentoring?', FAQ2_A: 'Slot gratis dibuka tiap awal bulan di nawala; daftarnya cepat penuh.',
            FAQ3_Q: 'Bolehkah mengutip tulisanmu?', FAQ3_A: 'Silakan, dengan atribusi dan tautan ke tulisan aslinya.',
            FAQ4_Q: 'Stack apa yang kamu pakai?', FAQ4_A: 'Berubah-ubah sesuai kebutuhan proyek — daftar terkini ada di halaman uses di blog.',
            CONTACT_SUB: 'Kolaborasi, undangan bicara, atau sekadar menyapa — semua saya baca.'
        }
    },
    'Berita / Majalah': {
        brand: 'Kabar Kota',
        description: 'media lokal independen — mengabarkan kota Anda dengan jurnalisme yang diverifikasi.',
        recipe: ['hero-editorial', 'stats', 'quote-single', 'cta'],
        copy: {
            TAGLINE: 'Kabar kotamu, diverifikasi sebelum dibagikan',
            HERO_BADGE: 'Terverifikasi Dewan Pers',
            HERO_CTA: 'Baca Edisi Hari Ini',
            HERO_IMG: 'Berita utama',
            HERO_CARD_T: '24/7',
            HERO_CARD_S: 'Redaksi siaga tiap hari',
            ABOUT_IMG: 'Ruang redaksi',
            STAT1_V: '30+', STAT1_L: 'Jurnalis & kontributor',
            STAT2_V: '80rb', STAT2_L: 'Pembaca harian',
            STAT3_V: '12', STAT3_L: 'Rubrik tetap',
            STAT4_V: '2015', STAT4_L: 'Berdiri sejak',
            FEAT1_T: 'Verifikasi berlapis', FEAT1_D: 'Setiap berita dicek minimal dua sumber.',
            FEAT2_T: 'Dekat dengan warga', FEAT2_D: 'Liputan dari kelurahan, bukan siaran pers.',
            FEAT3_T: 'Independen', FEAT3_D: 'Didanai pembaca dan iklan yang ditandai jelas.',
            HOME_ABOUT: 'Kabar Kota berdiri ketika berita tentang kota kami hanya jadi catatan kaki media nasional. Kami memilih meliputnya sendiri — dekat, akurat, dan berpihak pada warga.',
            CHECK1: 'Koreksi dipublikasikan terbuka.',
            CHECK2: 'Kanal aduan warga ditindaklanjuti redaksi.',
            CHECK3: 'Arsip berita terbuka gratis.',
            QUOTE1: 'Satu-satunya media yang meliput banjir di gang kami sampai tuntas.',
            QUOTE2: 'Beritanya cepat tapi tidak asal — langka sekarang ini.',
            QUOTE3: 'Rubrik akhir pekannya jadi bacaan wajib keluarga kami.',
            CTA_T: 'Dukung jurnalisme lokal',
            CTA_S: 'Berlangganan mulai Rp20.000/bulan — batalkan kapan saja.',
            ABOUT_STORY1: 'Kabar Kota berdiri tahun 2015, ketika kabar tentang kota kami hanya muncul di media nasional saat ada bencana atau skandal.',
            ABOUT_STORY2: 'Kami memilih hadir setiap hari: rapat dewan yang sepi peliput, UMKM yang tumbuh, dan trotoar yang tak kunjung diperbaiki.',
            VAL1_T: 'Verifikasi dulu', VAL1_D: 'Lebih baik terlambat sejam daripada salah selamanya.',
            VAL2_T: 'Berpihak pada warga', VAL2_D: 'Pertanyaan kami mewakili yang tidak bisa bertanya.',
            VAL3_T: 'Terbuka soal salah', VAL3_D: 'Koreksi dipublikasikan di tempat yang sama mencoloknya.',
            FAQ1_Q: 'Bagaimana mengirim informasi atau aduan?', FAQ1_A: 'Lewat kanal aduan warga di halaman kontak — identitas pelapor kami lindungi.',
            FAQ2_Q: 'Apa bedanya konten gratis dan berlangganan?', FAQ2_A: 'Berita harian gratis; liputan mendalam, arsip premium, dan edisi akhir pekan untuk pelanggan.',
            FAQ3_Q: 'Apakah menerima tulisan opini?', FAQ3_A: 'Ya — panduan panjang naskah dan honor ada di halaman kontak redaksi.',
            FAQ4_Q: 'Bagaimana kebijakan koreksi kalian?', FAQ4_A: 'Kesalahan dikoreksi secepatnya dan dicatat terbuka di bagian bawah artikel.',
            CONTACT_SUB: 'Kirim informasi, aduan warga, atau naskah opini.',
            ED_KICKER: 'Liputan utama',
            ED1_T: 'Trotoar rusak tiga tahun: ke mana anggaran perbaikan jalan kota?',
            ED2_T: 'Pasar pagi bertahan di tengah gempuran ritel modern',
            ED3_T: 'Cerita guru honorer di pinggiran yang menolak menyerah',
            ED4_T: 'Data: banjir kiriman makin sering, ini titik terparahnya',
            CATALOG_SUB: 'Rubrik dan liputan pilihan redaksi.',
            CARD_META: 'Liputan Khusus · 12 menit baca',
            CARD_DESC: 'Laporan mendalam dengan data dan narasumber berlapis.',
            CARD_PRICE: 'Premium',
            CARD_CTA: 'Baca'
        }
    },
    'Forum / Komunitas': {
        brand: 'Tukang Kode',
        description: 'komunitas developer Indonesia — tempat bertanya, berbagi, dan tumbuh bareng.',
        recipe: ['hero-centered', 'stats', 'features', 'quote-single', 'cta'],
        copy: {
            TAGLINE: 'Bertanya tidak dihakimi, menjawab dihargai',
            HERO_BADGE: '25.000+ anggota terdaftar',
            HERO_CTA: 'Gabung Gratis',
            HERO_IMG: 'Diskusi populer',
            HERO_CARD_T: '98%',
            HERO_CARD_S: 'Pertanyaan terjawab < 24 jam',
            ABOUT_IMG: 'Kopdar komunitas',
            STAT1_V: '25rb+', STAT1_L: 'Anggota',
            STAT2_V: '120rb+', STAT2_L: 'Diskusi',
            STAT3_V: '98%', STAT3_L: 'Terjawab dalam sehari',
            STAT4_V: '15', STAT4_L: 'Kota punya chapter',
            FEAT1_T: 'Ramah pemula', FEAT1_D: 'Tidak ada pertanyaan bodoh — aturan #1 di sini.',
            FEAT2_T: 'Moderasi aktif', FEAT2_D: 'Diskusi tetap sehat, spam dibersihkan cepat.',
            FEAT3_T: 'Dari online ke offline', FEAT3_D: 'Kopdar dan sesi belajar rutin di banyak kota.',
            HOME_ABOUT: 'Berawal dari grup chat 30 orang yang saling bantu debug tengah malam, kini menjadi forum developer dengan budaya yang kami jaga betul: saling mengangkat, bukan saling pamer.',
            CHECK1: 'Gratis selamanya untuk anggota.',
            CHECK2: 'Kanal lowongan kerja khusus anggota.',
            CHECK3: 'Kode etik ditegakkan moderator terpilih.',
            QUOTE1: 'Pertanyaan pertama saya dijawab lengkap dalam satu jam. Langsung betah.',
            QUOTE2: 'Dapat kerja remote pertama dari kanal loker komunitas ini.',
            QUOTE3: 'Kopdarnya seru — akhirnya ketemu langsung orang-orang yang biasa bantu di forum.',
            CTA_T: 'Developer tidak harus sendirian',
            CTA_S: 'Daftar gratis, langsung bisa ikut diskusi hari ini.',
            ABOUT_STORY1: 'Tukang Kode bermula dari grup chat 30 orang yang saling menemani debug tengah malam — kultur salingnya terbawa sampai sekarang.',
            ABOUT_STORY2: 'Forum ini dikelola relawan dan didanai komunitas, supaya keputusan selalu berpihak pada anggota, bukan pengiklan.',
            VAL1_T: 'Tidak ada pertanyaan bodoh', VAL1_D: 'Semua pernah jadi pemula; di sini itu diingat.',
            VAL2_T: 'Jawaban yang mendidik', VAL2_D: 'Bukan cuma potongan kode, tapi kenapa-nya.',
            VAL3_T: 'Sehat dijaga bersama', VAL3_D: 'Moderasi tegas pada toxic, longgar pada humor.',
            FAQ1_Q: 'Bagaimana cara bergabung?', FAQ1_A: 'Daftar gratis dengan email — langsung bisa membaca, bertanya, dan menjawab.',
            FAQ2_Q: 'Etika bertanya di forum ini?', FAQ2_A: 'Ceritakan konteks, apa yang sudah dicoba, dan pesan errornya — sisanya komunitas yang bantu.',
            FAQ3_Q: 'Apa itu poin reputasi?', FAQ3_A: 'Penghargaan dari anggota lain untuk jawaban yang membantu; membuka fitur moderasi bertahap.',
            FAQ4_Q: 'Adakah kegiatan offline?', FAQ4_A: 'Kopdar dan study group rutin di 15 kota — jadwalnya di topik pinned tiap chapter.',
            CONTACT_SUB: 'Laporan, kemitraan, atau usulan chapter kota baru.',
            CATALOG_SUB: 'Diskusi paling hangat pekan ini.',
            CARD_META: '42 balasan · aktif 1 jam lalu',
            CARD_DESC: 'Diskusi dengan jawaban terverifikasi dari kontributor senior.',
            CARD_PRICE: 'Terbuka',
            CARD_CTA: 'Ikut Diskusi'
        }
    },
    'Booking / Reservasi': {
        brand: 'Selaras Spa',
        description: 'spa dan pijat tradisional dengan terapis bersertifikat — reservasi online, tanpa antre.',
        recipe: ['hero-split', 'steps', 'features', 'quote-single', 'cta'],
        copy: {
            TAGLINE: 'Waktunya tubuhmu dirawat dengan benar',
            HERO_BADGE: 'Terapis bersertifikat',
            HERO_CTA: 'Reservasi Sekarang',
            HERO_IMG: 'Ruang perawatan',
            HERO_CARD_T: 'Slot pasti',
            HERO_CARD_S: 'Reservasi online, tanpa antre',
            ABOUT_IMG: 'Suasana spa',
            STAT1_V: '12', STAT1_L: 'Jenis perawatan',
            STAT2_V: '18', STAT2_L: 'Terapis bersertifikat',
            STAT3_V: '30rb+', STAT3_L: 'Sesi perawatan',
            STAT4_V: '4,9', STAT4_L: 'Rating pelanggan',
            FEAT1_T: 'Booking 1 menit', FEAT1_D: 'Pilih perawatan, terapis, dan jam dari HP.',
            FEAT2_T: 'Datang langsung mulai', FEAT2_D: 'Ruangan sudah siap saat Anda tiba.',
            FEAT3_T: 'Produk alami', FEAT3_D: 'Minyak dan lulur racikan sendiri, teruji aman.',
            HOME_ABOUT: 'Selaras dimulai dari keyakinan sederhana: relaksasi tidak seharusnya diawali antre panjang. Sistem reservasi kami memastikan waktu Anda di sini hanya untuk satu hal — istirahat.',
            CHECK1: 'Reschedule gratis hingga 3 jam sebelum sesi.',
            CHECK2: 'Ruang privat untuk pasangan dan keluarga.',
            CHECK3: 'Paket langganan dengan harga anggota.',
            QUOTE1: 'Booking jam 8, jam 8 tepat sudah di ruang perawatan. Luar biasa.',
            QUOTE2: 'Pijatnya juara, tempatnya tenang, wanginya bikin ketagihan.',
            QUOTE3: 'Langganan bulanan di sini adalah bentuk sayang diri terbaik.',
            CTA_T: 'Badanmu sudah kasih kode',
            CTA_S: 'Slot sore selalu cepat penuh — amankan jadwalmu.',
            ABOUT_STORY1: 'Selaras dibuka oleh terapis senior yang lelah melihat pelanggan mengantre dua jam untuk relaksasi tiga puluh menit.',
            ABOUT_STORY2: 'Maka semuanya kami rancang ulang dari nol: reservasi pasti, ruangan disiapkan sebelum Anda tiba, dan terapis yang tidak diburu target.',
            VAL1_T: 'Waktu Anda dihormati', VAL1_D: 'Sesi mulai tepat menit yang Anda pesan.',
            VAL2_T: 'Terapis sejahtera', VAL2_D: 'Jadwal manusiawi — kualitas pijat mengikuti.',
            VAL3_T: 'Bersih tanpa kompromi', VAL3_D: 'Linen sekali pakai, minyak segar tiap sesi.',
            SVC1_T: 'Pijat Tradisional', SVC1_D: 'Teknik urut Jawa 60–90 menit untuk pegal dan sirkulasi.',
            SVC2_T: 'Aromaterapi & Refleksi', SVC2_D: 'Kombinasi titik refleksi dan minyak esensial racikan sendiri.',
            SVC3_T: 'Paket Pasangan', SVC3_D: 'Ruang privat berdua dengan teh herbal selepas sesi.',
            FAQ1_Q: 'Bagaimana cara reservasi?', FAQ1_A: 'Lewat halaman booking: pilih perawatan, terapis, dan jam — konfirmasi instan ke WhatsApp.',
            FAQ2_Q: 'Bagaimana jika terlambat datang?', FAQ2_A: 'Toleransi 15 menit; lewat itu durasi menyesuaikan sisa slot agar pelanggan berikutnya tidak mundur.',
            FAQ3_Q: 'Bisakah memilih terapis yang sama lagi?', FAQ3_A: 'Bisa — nama terapis muncul saat booking, dan riwayat Anda menyimpannya.',
            FAQ4_Q: 'Adakah paket langganan?', FAQ4_A: 'Ada, 4 dan 8 sesi per bulan dengan harga anggota — bisa dipakai keluarga inti.',
            CONTACT_SUB: 'Reservasi, ubah jadwal, atau tanya perawatan yang cocok.',
            STEPS_T: 'Reservasi dalam tiga langkah',
            STEP1_T: 'Pilih perawatan', STEP1_D: 'Lihat menu perawatan beserta durasi dan harganya.',
            STEP2_T: 'Pilih terapis & jam', STEP2_D: 'Slot kosong tampil langsung — konfirmasi instan ke WhatsApp.',
            STEP3_T: 'Datang & rileks', STEP3_D: 'Ruangan sudah disiapkan sebelum Anda tiba.'
        }
    }
};

/**
 * Pack untuk satu jenis website, dicari dari labelnya. Jenis aplikasi internal tidak punya
 * pack (demonya contoh dashboard, bukan situs publik); jenis publik tanpa pack — seharusnya
 * tidak ada — jatuh ke pack generik agar demo tetap terakit.
 */
export function typePackFor(type: TokenaiWebsiteType): TokenaiTypePack {
    return PACKS[type.label] ?? {
        brand: 'Usaha Anda',
        description: 'contoh halaman jadi yang dirakit dari arketipe kit ini.',
        recipe: [...TOKENAI_DEFAULT_HOME_RECIPE],
        copy: {}
    };
}
